### ISSUE TITLE
Missing model for half-life prediction

### ISSUE THREAD

**Issue by slebedeva** [huangwenze/PrismNet_analysis#1]
Hi! I could not find the Gradient Boosting Tree model that you used in the paper to predict RNA half-lives. Would you be so kind to share it? Thank you very much!

**Comment by huangwenze** [comment]
OK, Thanks for your Interest. We will prepare the GBT code for open source as soon as possible, when it is ready, we will let you know.


best,
Wenze
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangwenze/PrismNet_analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月27日(星期四) 下午4:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[huangwenze/PrismNet_analysis] Missing model for half-life prediction (#1)





 
Hi! I could not find the Gradient Boosting Tree model that you used in the paper to predict RNA half-lives. Would you be so kind to share it? Thank you very much!
